name: Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build:
    name: Build dist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install dependencies
      run: |
        pip install build tomli tomli-w
    - name: Build web assets
      run: |
        cd web
        npm install
        npm run build
    - name: Build Python packages
      run: |
        # Build original memos package
        python -m build
        # Create and build pensiev package
        python create_pensiev_toml.py
        cp pyproject_pensiev.toml pyproject.toml
        mkdir pensiev_dist
        python -m build --outdir pensiev_dist
        # Restore original pyproject.toml
        git checkout pyproject.toml
    - name: Upload memos dist
      uses: actions/upload-artifact@v4
      with:
        name: memos-dist
        path: dist/*
    - name: Upload pensiev dist
      uses: actions/upload-artifact@v4
      with:
        name: pensiev-dist
        path: pensiev_dist/*

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v5
        with:
          mode: HYBRID
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{steps.github_release.outputs.changelog}}
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pypi-memos:
    needs: release
    name: Upload memos to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/memos
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: memos-dist
        path: dist
    - name: Publish memos package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist

  pypi-pensiev:
    needs: release
    name: Upload pensiev to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/pensiev
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: pensiev-dist
        path: dist
    - name: Publish pensiev package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist